version: '3'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
    environment:
      USER_CHOCOLATEEN_PASSWORD: motdepassechoco
      USER_VAUGIE_G_PASSWORD: motdepassevaugie
      USER_I_DONT_KNOW_PASSWORD: motdepasseidk
      USER_NASSO_PASSWORD: motdepassenasso